### PR TITLE
Convert log-viewer to Typescript

### PR DESCRIPTION
**Pull request by kjonesffdc**
As part of this I have moved the extension into the lana directory as I was seeing strange behaviour from VSCode with one Typescipt project inside another. The lana package.json script will build the log-viewer for you and copy it over to the extension directory into 'out'.

I have done almost no testing of the code converted over to Typescript. I think we would be better merging this and then we can work on smaller stories to incrementally improve. Next up I would like to re-enable the log-viewer tests.

### CODE REVIEW

**Comment by lcotterffdc** [comment]
@kjonesffdc Since code has moved to lana, `vsce package` needs running from lana folder.
Same goes for the npm commands I guess we need to update the `BUILDING.MD` or move package.json back to root?

**Comment by lcotterffdc** [comment]
looks like I also need to open vscode in `lana` dir to be able to use the debug stuff.
having to have 2 vscode instances for lana and log-viewer is going to be a little annoying.

**Comment by kjonesffdc** [comment]
Having them nested would be a bit easier but really I think we want to head towards being able to develop on log-viewer outside of VSCode. This is what I did with the dep. explorer and it was so much easier/quicker. Obviously the original log-viewer allowed this, but the capability got lost when it was ported into the VSCode model.

**Comment by lcotterffdc** [comment]
I gave this a manual test, everything seems ok except the collapse in the call tree is broken.

**Comment by lcotterffdc** [comment]
> Having them nested would be a bit easier but really I think we want to head towards being able to develop on log-viewer outside of VSCode. This is what I did with the dep. explorer and it was so much easier/quicker. Obviously the original log-viewer allowed this, but the capability got lost when it was ported into the VSCode model.

@kjonesffdc I think i disagree slightly, If you view this as the repo for the extension then it makes more sense to me that i can run the commands from root to build everything for the extension. 

If we want to move the log viewer (flamegraph) and log parser into dependencies then I am all for that and it make sense to me. I guess this repo would hold only the vscode bits (commands and views etc)

**Comment by sjonwilson** [comment]
I haven't done any debugging yet, but I think I agree with @lcotterffdc - I liked debugging the original as stand-alone code. It was very quick as you could just edit the JavaScript and reload the page.

**Review by sjonwilson — APPROVED** [review]

**Pull request merged**
